# Generated by Django 5.0.7 on 2024-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='video',
        ),
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
