# Generated by Django 5.0.7 on 2024-09-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_remove_picture_video_picture_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='picture',
            table='picture',
        ),
    ]
