# Generated by Django 5.0.7 on 2024-09-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_alter_picture_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
