# Generated by Django 5.0.7 on 2024-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0007_alter_picture_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='picture',
        ),
        migrations.AddField(
            model_name='picture',
            name='pic_name',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='picture',
            name='pic_url',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
