# Generated by Django 5.0.7 on 2024-09-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0008_remove_picture_name_remove_picture_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pic_time_end',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='picture',
            name='pic_time_start',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
