# Generated by Django 5.0.7 on 2024-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0009_picture_pic_time_end_picture_pic_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pic_Type',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='picture',
            name='pic_channel',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
