# Generated by Django 5.0.7 on 2024-09-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0010_picture_pic_type_picture_pic_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='pic_time_end',
            new_name='pic_time',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='pic_time_start',
        ),
    ]
