# Generated by Django 5.0.7 on 2024-09-23 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0011_rename_pic_time_end_picture_pic_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='picture',
            table='picture',
        ),
    ]
