# Generated by Django 5.0.7 on 2024-09-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0012_alter_picture_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='pic_Type',
            new_name='pic_type',
        ),
    ]
