# Generated by Django 5.0.7 on 2024-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0013_rename_pic_type_picture_pic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic_time',
            field=models.DateTimeField(default=0, max_length=300),
        ),
    ]
