# Generated by Django 5.0.7 on 2024-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caqulate',
            fields=[
                ('the_id', models.IntegerField(primary_key=True, serialize=False)),
                ('satution', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=50)),
                ('caqu_settings', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'caqulate',
            },
        ),
    ]
