# Generated by Django 5.0.7 on 2024-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caqulate',
            name='degree',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='caqulate',
            name='open_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caqulate',
            name='pinglv',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
