# Generated by Django 5.0.7 on 2024-09-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0002_caqulate_degree_caqulate_open_close_caqulate_pinglv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caqulate',
            old_name='satution',
            new_name='satuation',
        ),
    ]
