# Generated by Django 5.0.7 on 2024-09-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0003_rename_satution_caqulate_satuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caqulate',
            name='update_time',
            field=models.CharField(max_length=50),
        ),
    ]
