# Generated by Django 5.0.7 on 2024-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0004_alter_caqulate_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caqulate',
            name='the_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
