# Generated by Django 5.0.7 on 2024-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0006_alter_caqulate_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caqulate',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
