# Generated by Django 5.0.7 on 2024-09-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0007_alter_caqulate_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caqulate',
            name='degree',
            field=models.CharField(default='50', max_length=50),
        ),
        migrations.AlterField(
            model_name='caqulate',
            name='pinglv',
            field=models.CharField(default='50', max_length=50),
        ),
    ]
