# Generated by Django 5.0.7 on 2024-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0008_alter_caqulate_degree_alter_caqulate_pinglv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caqulate_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('open_close', models.BooleanField(default=False)),
                ('degree', models.CharField(default='50', max_length=50)),
                ('pinglv', models.CharField(default='50', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='caqulate',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='caqulate',
            name='open_close',
        ),
        migrations.RemoveField(
            model_name='caqulate',
            name='pinglv',
        ),
        migrations.RemoveField(
            model_name='caqulate',
            name='satuation',
        ),
    ]
