# Generated by Django 5.0.7 on 2024-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0009_caqulate_setting_remove_caqulate_degree_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caqulate_setting',
        ),
        migrations.AddField(
            model_name='caqulate',
            name='car_degree',
            field=models.CharField(default='50', max_length=50),
        ),
        migrations.AddField(
            model_name='caqulate',
            name='car_open_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caqulate',
            name='car_pinglv',
            field=models.CharField(default='50', max_length=50),
        ),
        migrations.AddField(
            model_name='caqulate',
            name='peo_degree',
            field=models.CharField(default='50', max_length=50),
        ),
        migrations.AddField(
            model_name='caqulate',
            name='peo_open_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caqulate',
            name='peo_pinglv',
            field=models.CharField(default='50', max_length=50),
        ),
    ]
