# Generated by Django 5.0.7 on 2024-09-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0010_delete_caqulate_setting_caqulate_car_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caqulate',
            name='satuation',
            field=models.BooleanField(default=False),
        ),
    ]
