# Generated by Django 5.0.7 on 2024-09-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0011_caqulate_satuation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caqulate',
            name='caqu_settings',
        ),
    ]
