# Generated by Django 5.0.7 on 2024-10-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caqulate', '0012_remove_caqulate_caqu_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caqulate',
            name='satuation',
            field=models.CharField(max_length=20),
        ),
    ]
