# Generated by Django 3.2.25 on 2024-10-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='开始时间')),
                ('end_datetime', models.DateTimeField(verbose_name='结束时间')),
                ('channel_type', models.CharField(max_length=255, verbose_name='通道类型')),
                ('alert_type', models.CharField(max_length=255, verbose_name='告警类型')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
