# Generated by Django 3.2.25 on 2024-10-09 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_alert_type', models.CharField(choices=[('people_count', '人数统计'), ('vehicle_count', '车辆统计')], max_length=15, verbose_name='告警类型')),
                ('human_alert_type', models.CharField(choices=[('people_count', '人数统计'), ('vehicle_count', '车辆统计')], max_length=15, verbose_name='告警类型')),
                ('human_switch_status', models.CharField(choices=[('off', '关'), ('on', '开')], default='off', max_length=20, verbose_name='开关状态')),
                ('car_switch_status', models.CharField(choices=[('off', '关'), ('on', '开')], default='off', max_length=20, verbose_name='开关状态')),
                ('human_sensitivity', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='灵敏度')),
                ('car_sensitivity', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='灵敏度')),
                ('human_report_frequency', models.IntegerField(default=5, verbose_name='上报频率(秒)')),
                ('car_report_frequency', models.IntegerField(default=5, verbose_name='上报频率(秒)')),
                ('updatetime', models.TimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '算法配置',
                'verbose_name_plural': '算法配置',
            },
        ),
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('status', models.CharField(choices=[('Not configured', '未配置'), ('online', '在线'), ('offline', '离线')], default='未配置', max_length=120, verbose_name='通道状态')),
                ('rtsp_url', models.CharField(default='rtsp://xxxx', max_length=255, verbose_name='RTSP地址')),
                ('channel_name', models.CharField(max_length=255, verbose_name='通道名称')),
                ('perimeter', models.CharField(max_length=255, null=True, verbose_name='周界')),
                ('updatetime', models.TimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '通道管理',
                'verbose_name_plural': '通道管理',
            },
        ),
    ]
