# Generated by Django 5.0.7 on 2024-09-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
