# Generated by Django 3.2.25 on 2024-10-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='摄像头名称')),
                ('updatetime', models.TimeField(auto_now=True, verbose_name='修改时间')),
                ('file', models.FileField(upload_to='videos')),
            ],
            options={
                'verbose_name': '摄像头',
                'verbose_name_plural': '摄像头',
            },
        ),
    ]
